(function(b){var c=window.AmazonUIPageJS||window.P,q=c._namespace||c.attributeErrors,a=q?q("HuddlesChatboxJS",""):c;a.guardFatal?a.guardFatal(b)(a,window):a.execute(function(){b(a,window)})})(function(b,c,q){b.when("A","huddles-core","ready").register("huddles-chatbox-interaction",function(a,e){function m(){if(r.width()&&r.offset()){var a=r.width();return a+r.offset().left-b.width()>.9*a?h.css("right",k):h.css("right",k+a)}a=parseInt(u.css("padding-right"),10);return h.css("right",k+a)}function d(){if(0!==
t.length&&null!==t.position()){var a=b.height(),g=Math.max(0,t.position().top+t.height()-b.scrollTop());300>a-g?p.height(0):p.height(Math.min(500,a-g)-v.outerHeight())}}function l(){d();m()}var b=a.$(c),u=a.$("body"),t=a.$("#navbar, #navWrapper, .header-contents-container").first(),r=a.$("#nav-flyout-ewc"),h=a.$(".huddles-chatbox"),p=a.$(".huddles-chatbox__content"),v=a.$(".huddles-chatbox__toolbar"),f=a.$(".huddles-chatbox__toolbar-minimize"),k=parseInt(h.css("right"),10);setInterval(m,3E3);b.resize(a.debounce(l,
100));b.scroll(a.debounce(d,100));return{minimizeChatbox:function(d){h.show();d?(p.hide(),f.addClass("huddles-chatbox__vertical-flip")):a.slideUp(p,200,"ease-out",function(){f.addClass("huddles-chatbox__vertical-flip")})},maximizeChatbox:function(){},restoreChatbox:function(d){p.show();l();d?(h.show(),f.removeClass("huddles-chatbox__vertical-flip")):a.slideDown(h,200,"ease-out",function(){f.removeClass("huddles-chatbox__vertical-flip")})},closeChatbox:function(){a.slideUp(h,200,"ease-out")}}});"use strict";
b.when("A","ready").register("huddles-chatbox-storage",function(a){function e(){try{return d&&"sessionStorage"in c&&null!==c.sessionStorage&&sessionStorage}catch(a){return!1}}var m="huddle-chatbox"+c.location.pathname,d=!1;return{enableSessionStorage:function(){d=!0},getChatboxState:function(){if(e())return JSON.parse(sessionStorage.getItem(m))||{};d&&b.log("sessionStorage not available","WARN");return{}},setChatboxState:function(a){e()&&sessionStorage.setItem(m,JSON.stringify(a))},DISPLAY_CODE:{MINIMIZED:"MINIMIZED",
MAXIMIZED:"MAXIMIZED",NORMAL:"NORMAL"}}});"use strict";b.when("A","ready").register("huddles-chatbox-metrics",function(a){return{logCounter:function(a,b){c.ue&&c.ue.count&&(a="HuddlesChatbox."+a,c.ue.count(a,(c.ue.count(a)||0)+(b||1)))}}});"use strict";b.register("huddles-chatbox-feature-config",function(){return{chatbox:!0}});"use strict";b.when("A","huddles-chatbox-feature-config","ready").execute(function(a,e){function m(a){var b=c.ue.sn||c.ue_sn;return b&&b.substring(b.length-a.length,b.length)===
a}if(!c.ue||"PackageProgressTracker"!==c.ue_pty||m("amazon.com"))c.HuddlesChatboxConfig?b.log("Chatbox config already registered","WARN"):e.chatbox&&(c.HuddlesChatboxConfig={},a.get("/conversations/chatbox-config",{params:{originalUrl:encodeURIComponent(c.location.href),pty:c.ue_pty},timeout:4E4,success:function(d){var e;if(d.chatboxSupported){if(a.objectIsEmpty(d.endpointConfig)||a.objectIsEmpty(d.startupArgs)){b.log("Invalid Huddles chatbox config","ERROR");c.HuddlesChatboxConfig=null;return}e=
{chatboxSupported:!0,chatboxEndpointConfig:d.endpointConfig,chatboxStartupArgs:a.$.extend({},d.startupArgs,{renderContext:{isRemote:!0}}),enableSessionStorage:d.enableSessionStorage}}else e={chatboxSupported:!1},b.log("Chatbox functionality suppressed","WARN");b.declare("huddles-chatbox-config",e);c.HuddlesChatboxConfig=e;d.chatboxContainer&&a.$(d.chatboxContainer).appendTo("body")},error:function(a,e,m){c.HuddlesChatboxConfig=null;b.log("Failed to get Huddles chatbox config. "+e+": "+m,"ERROR")}}))});
b.when("A","huddles-core","huddles-chatbox-interaction","huddles-chatbox-storage","huddles-chatbox-metrics","huddles-chatbox-config","ready").register("huddles-chatbox",function(a,e,c,d,l,q){function u(a){f[n||"INBOX"]=a;d.setChatboxState(f)}function t(g){var b=g.displayCode||k.NORMAL,d=a.$.extend({},p,g);g.showEmbedded&&g.container?(g.container instanceof a.$&&(g.container=g.container.get(0)),e.startHuddleApp(g.container,v,d),l.logCounter("Rendered.Embedded")):(b===k.MINIMIZED?c.minimizeChatbox(!0):
(g=document.querySelector(".huddles-chatbox__content"),e.startHuddleApp(g,v,d),b===k.MAXIMIZED?(c.restoreChatbox(!0),c.maximizeChatbox()):c.restoreChatbox()),f={},u(b),l.logCounter("Rendered."+b))}function r(a){n=null;t(a||{})}function h(a){if(!a||!a.huddleId)return b.log("Required render parameter huddleId missing for renderHuddleChat","FATAL"),!1;n=a.huddleId;t(a)}var p=q.chatboxStartupArgs,v=q.chatboxEndpointConfig;q.enableSessionStorage&&d.enableSessionStorage();var f=d.getChatboxState(),k=d.DISPLAY_CODE,
n;a.objectIsEmpty(f)||a.each(f,function(a,b){"INBOX"===b?r({showEmbedded:!1,displayCode:a}):h({huddleId:b,showEmbedded:!1,displayCode:a})});return{renderInbox:r,renderHuddleChat:h,restoreChatbox:function(){if(!n||!f[n]||f[n]===k.MINIMIZED){var b={};n&&(b.huddleId=n);var b=a.$.extend({},p,b),d=document.querySelector(".huddles-chatbox__content");e.startHuddleApp(d,v,b)}c.restoreChatbox();u(k.NORMAL);l.logCounter("Restored")},closeChatbox:function(b){b?(b instanceof a.$&&(b=b.get(0)),e.closeHuddleApp(b),
l.logCounter("Closed.Embedded")):(c.closeChatbox(),b=document.querySelector(".huddles-chatbox__content"),e.closeHuddleApp(b),f={},d.setChatboxState(f),l.logCounter("Closed"))},minimizeChatbox:function(){c.minimizeChatbox();var a=document.querySelector(".huddles-chatbox__content");e.closeHuddleApp(a);u(k.MINIMIZED);l.logCounter("Minimized")},maximizeChatbox:function(){c.maximizeChatbox();u(k.MINIMIZED);l.logCounter("Maximized")},setPersonaName:e.setPersonaName,deprecated_watchPartyEvent:e.deprecated_watchPartyEvent}});
"use strict";b.when("A","huddles-chatbox","ready").execute(function(a,b){a.declarative("minimizeChatbox","click",function(c){a.$(".huddles-chatbox__content").is(":visible")?b.minimizeChatbox():b.restoreChatbox()});a.declarative("closeChatbox","click",function(a){b.closeChatbox()})})});